/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "sys_clocks.h"
#include "lpuart.h"
#include "uart_protocol.h"
#include "state_machine.h"
#include "motor.h"
#include "tim.h"



int main(void)
{
	SystemClockSetup();
	Motor_Init();
	Tim15Init();
	Tim15_Start();
	LPUART1_config();
	StateMachine_Init();

//	Motor_Right();

    while(1)
    {
//    	UART_Protocol_Process();
//    	StateMachine_Run();
//    	Motor_Off();
    }
}









