/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "sys_clocks.h"
#include "lpuart.h"
#include "uart_protocol.h"
#include "state_machine.h"
#include "motor.h"
#include "tim.h"
#include "i2c.h"
#include "oled.h"
#include "joy.h"
#include "encoder.h"

volatile uint32_t encoder_cnt;
volatile int32_t encoder_angle;
volatile int32_t encoder_rpm;
int main(void)
{
	SystemClockSetup();
	Motor_Init();
	Tim15Init();
	Tim3Init();
	Tim15_Start();
	Tim3_Start();
	LPUART1_config();
	StateMachine_Init();
	I2C1_Init();
	OLED_Init();
	OLED_Clear();
	joy_init();

	encoder_init();

    while(1)
    {
    	encoder_Update();
    	encoder_angle = encoder_GetPositionAngle();
    	encoder_rpm = encoder_GetSpeed();

    	UART_Protocol_Process();
    	StateMachine_Run();
    }
}









