/*
 * tim.c
 *
 *  Created on: Apr 29, 2026
 *      Author: kapi-
 */

#include "main.h"
#include "sys_clocks.h"
#include "tim.h"
#include "motor.h"

// TIM15 CHANNEL 1 - PWM
// TIM3 CHANNEL 1 - ENC A
// TIM3 CHANNEL 2 - ENC B

void Tim15Init(void)
{
	RCC->APB2ENR &= ~(RCC_APB2ENR_TIM15EN);
	RCC->APB2ENR |= RCC_APB2ENR_TIM15EN;

	TIM15->CNT = 0;
}

void Tim3Init(void)
{
	RCC->APB1ENR1 &= ~(RCC_APB1ENR1_TIM3EN);
	RCC->APB1ENR1 |= RCC_APB1ENR1_TIM3EN;

	TIM3->CNT = 0;
}

void Tim15_Start(void)
{
	TIM15->PSC = 79;
	TIM15->ARR = 999;

	TIM15->CCR1 = Speed(50);

	TIM15->CCMR1 &= ~(TIM_CCMR1_OC1M);
	TIM15->CCMR1 |= (TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2);
	TIM15->CCMR1 |= TIM_CCMR1_OC1PE;

	TIM15->CCER &= ~(TIM_CCER_CC1P);
	TIM15->CCER |= TIM_CCER_CC1E;

	TIM15->BDTR |= TIM_BDTR_MOE;
	TIM15->CR1  |= TIM_CR1_CEN;
}

void Tim3_Start(void)
{
	TIM3->PSC = 0;
	TIM3->ARR = 0XFFFF;

	TIM3->SMCR &= ~(TIM_SMCR_SMS);
	TIM3->SMCR |= TIM_SMCR_SMS_0 | TIM_SMCR_SMS_1;

	TIM3->CCMR1 &= ~(TIM_CCMR1_CC1S);
	TIM3->CCMR1 &= ~(TIM_CCMR1_CC2S);

	TIM3->CCMR1 |= TIM_CCMR1_CC1S_0;
	TIM3->CCMR1 |= TIM_CCMR1_CC2S_0;

	TIM3->CCER &= ~(TIM_CCER_CC1P);
	TIM3->CCER &= ~(TIM_CCER_CC2P);

	TIM3->CCER |= TIM_CCER_CC1E;
	TIM3->CCER |= TIM_CCER_CC2E;

	TIM3->CR1  |= TIM_CR1_CEN;
}






